import type { AppSnapshot, Category, User } from './domain'

function now() {
  return '2026-05-04T00:00:00.000Z'
}

export const DEMO_EMAIL = 'demo@cashpilot.app'
export const DEMO_PASSWORD = 'demo123456'

const defaultCategorySeed: Array<[string, string, Category['group']]> = [
  ['cat-salary', '薪資', 'income'],
  ['cat-subsidy', '租屋補貼', 'income'],
  ['cat-rent', '房租', 'housing'],
  ['cat-subscription', '訂閱', 'subscription'],
  ['cat-debt', '卡費與債務', 'debt'],
  ['cat-daily', '生活支出', 'other'],
  ['cat-invest', '投資', 'investment'],
  ['cat-travel', '旅行', 'travel'],
  ['cat-purchase', '大型購買', 'shopping'],
]

function createUser(): User {
  return {
    id: 'usr-demo',
    email: DEMO_EMAIL,
    displayName: 'YEH CHUNCHENG',
    createdAt: now(),
    updatedAt: now(),
  }
}

export function createDefaultCategories(
  userId: string,
  options?: {
    idPrefix?: string
  },
): Category[] {
  const prefix = options?.idPrefix ? `${options.idPrefix}-` : ''

  return defaultCategorySeed.map(([id, name, group]) => ({
    id: `${prefix}${id}`,
    userId,
    name,
    group,
    createdAt: now(),
    updatedAt: now(),
  }))
}

export function createDemoSnapshot(): AppSnapshot {
  const user = createUser()
  const categories = createDefaultCategories(user.id)

  return {
    users: [user],
    categories,
    accounts: [
      {
        id: 'acc-bank',
        userId: user.id,
        name: '台新銀行',
        type: 'bank',
        currency: 'TWD',
        balanceMinor: 1881800,
        isActive: true,
        createdAt: now(),
        updatedAt: now(),
      },
      {
        id: 'acc-invest',
        userId: user.id,
        name: '富果投資',
        type: 'investment',
        currency: 'TWD',
        balanceMinor: 437200,
        isActive: true,
        createdAt: now(),
        updatedAt: now(),
      },
      {
        id: 'acc-yushan',
        userId: user.id,
        name: '玉山信用卡',
        type: 'credit_card',
        currency: 'TWD',
        balanceMinor: 0,
        creditLimitMinor: 9000000,
        billingDay: 1,
        dueDay: 10,
        isActive: true,
        createdAt: now(),
        updatedAt: now(),
      },
      {
        id: 'acc-cathay',
        userId: user.id,
        name: '國泰信用卡',
        type: 'credit_card',
        currency: 'TWD',
        balanceMinor: 0,
        creditLimitMinor: 12000000,
        billingDay: 2,
        dueDay: 13,
        isActive: true,
        createdAt: now(),
        updatedAt: now(),
      },
      {
        id: 'acc-union',
        userId: user.id,
        name: '聯邦信用卡',
        type: 'credit_card',
        currency: 'TWD',
        balanceMinor: 0,
        creditLimitMinor: 7000000,
        billingDay: 3,
        dueDay: 18,
        isActive: true,
        createdAt: now(),
        updatedAt: now(),
      },
      {
        id: 'acc-loan',
        userId: user.id,
        name: '學貸',
        type: 'loan',
        currency: 'TWD',
        balanceMinor: 7823300,
        isActive: true,
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    transactions: [
      {
        id: 'txn-salary-apr',
        userId: user.id,
        accountId: 'acc-bank',
        date: '2026-04-05',
        amountMinor: 5107000,
        direction: 'income',
        categoryId: 'cat-salary',
        note: '四月薪資',
        isRecurring: true,
        createdAt: now(),
        updatedAt: now(),
      },
      {
        id: 'txn-rent-apr',
        userId: user.id,
        accountId: 'acc-bank',
        date: '2026-04-05',
        amountMinor: 1500000,
        direction: 'expense',
        categoryId: 'cat-rent',
        note: '四月房租',
        isRecurring: true,
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    bills: [
      {
        id: 'bill-yushan-2026-05',
        userId: user.id,
        accountId: 'acc-yushan',
        name: '玉山信用卡',
        billType: 'credit_card',
        statementMonth: '2026-05',
        totalAmountMinor: 1433700,
        paidAmountMinor: 0,
        dueDate: '2026-05-10',
        status: 'unpaid',
        canInstallment: true,
        nonInstallmentAmountMinor: 298700,
        installmentEligibleAmountMinor: 1135000,
        createdAt: now(),
        updatedAt: now(),
      },
      {
        id: 'bill-cathay-2026-05',
        userId: user.id,
        accountId: 'acc-cathay',
        name: '國泰信用卡',
        billType: 'credit_card',
        statementMonth: '2026-05',
        totalAmountMinor: 1104600,
        paidAmountMinor: 0,
        dueDate: '2026-05-13',
        status: 'unpaid',
        canInstallment: true,
        nonInstallmentAmountMinor: 234600,
        installmentEligibleAmountMinor: 870000,
        createdAt: now(),
        updatedAt: now(),
      },
      {
        id: 'bill-rent-2026-05',
        userId: user.id,
        name: '五月房租',
        billType: 'rent',
        totalAmountMinor: 1500000,
        paidAmountMinor: 0,
        dueDate: '2026-05-05',
        status: 'unpaid',
        canInstallment: false,
        createdAt: now(),
        updatedAt: now(),
      },
      {
        id: 'bill-union-2026-05',
        userId: user.id,
        accountId: 'acc-union',
        name: '聯邦信用卡',
        billType: 'credit_card',
        statementMonth: '2026-05',
        totalAmountMinor: 252500,
        paidAmountMinor: 0,
        dueDate: '2026-05-18',
        status: 'unpaid',
        canInstallment: false,
        createdAt: now(),
        updatedAt: now(),
      },
      {
        id: 'bill-loan-2026-05',
        userId: user.id,
        accountId: 'acc-loan',
        name: '學貸',
        billType: 'loan',
        totalAmountMinor: 320000,
        paidAmountMinor: 0,
        dueDate: '2026-05-26',
        status: 'unpaid',
        canInstallment: false,
        createdAt: now(),
        updatedAt: now(),
      },
    ],
    recurringRules: [
      {
        id: 'rule-salary',
        userId: user.id,
        name: '薪水',
        amountMinor: 5107000,
        direction: 'income',
        accountId: 'acc-bank',
        categoryId: 'cat-salary',
        frequency: 'monthly',
        dayOfMonth: 5,
        uncertainty: 'fixed',
        includeInBaseScenario: true,
        startDate: '2026-01-01',
        isActive: true,
      },
      {
        id: 'rule-rent-subsidy',
        userId: user.id,
        name: '租屋補貼',
        amountMinor: 360000,
        accountId: 'acc-bank',
        direction: 'income',
        categoryId: 'cat-subsidy',
        frequency: 'monthly',
        dayOfMonth: 20,
        uncertainty: 'variable_date',
        includeInBaseScenario: false,
        startDate: '2026-01-01',
        isActive: true,
      },
      {
        id: 'rule-rent',
        userId: user.id,
        name: '房租',
        amountMinor: 1500000,
        paymentAccountId: 'acc-bank',
        direction: 'expense',
        categoryId: 'cat-rent',
        frequency: 'monthly',
        dayOfMonth: 5,
        uncertainty: 'fixed',
        includeInBaseScenario: true,
        startDate: '2026-01-01',
        isActive: true,
      },
      {
        id: 'rule-patreon',
        userId: user.id,
        name: 'Patreon',
        amountMinor: 100000,
        paymentAccountId: 'acc-union',
        direction: 'expense',
        categoryId: 'cat-subscription',
        frequency: 'monthly',
        dayOfMonth: 12,
        uncertainty: 'fixed',
        includeInBaseScenario: true,
        startDate: '2026-01-01',
        isActive: true,
      },
      {
        id: 'rule-fanbox',
        userId: user.id,
        name: 'FANBOX',
        amountMinor: 20000,
        paymentAccountId: 'acc-union',
        direction: 'expense',
        categoryId: 'cat-subscription',
        frequency: 'monthly',
        dayOfMonth: 12,
        uncertainty: 'fixed',
        includeInBaseScenario: true,
        startDate: '2026-01-01',
        isActive: true,
      },
      {
        id: 'rule-ifmobile',
        userId: user.id,
        name: 'IFMOBILE',
        amountMinor: 29000,
        paymentAccountId: 'acc-union',
        direction: 'expense',
        categoryId: 'cat-subscription',
        frequency: 'monthly',
        dayOfMonth: 16,
        uncertainty: 'fixed',
        includeInBaseScenario: true,
        startDate: '2026-01-01',
        isActive: true,
      },
      {
        id: 'rule-unknown-subscription',
        userId: user.id,
        name: '不明會員',
        amountMinor: 9000,
        paymentAccountId: 'acc-union',
        direction: 'expense',
        categoryId: 'cat-subscription',
        frequency: 'monthly',
        dayOfMonth: 16,
        uncertainty: 'fixed',
        includeInBaseScenario: true,
        startDate: '2026-01-01',
        isActive: true,
      },
    ],
    installmentPlans: [],
    goals: [
      {
        id: 'goal-emergency-10k',
        userId: user.id,
        name: '緊急預備金 10,000',
        targetAmountMinor: 1000000,
        currentAmountMinor: 1881800,
        priority: 'high',
        goalType: 'emergency_fund',
        monthlyContributionMinor: 0,
        status: 'completed',
      },
      {
        id: 'goal-emergency-30k',
        userId: user.id,
        name: '緊急預備金 30,000',
        targetAmountMinor: 3000000,
        currentAmountMinor: 1881800,
        priority: 'high',
        goalType: 'emergency_fund',
        monthlyContributionMinor: 0,
        status: 'active',
      },
      {
        id: 'goal-emergency-100k',
        userId: user.id,
        name: '緊急預備金 100,000',
        targetAmountMinor: 10000000,
        currentAmountMinor: 1881800,
        priority: 'high',
        goalType: 'emergency_fund',
        monthlyContributionMinor: 0,
        status: 'active',
      },
      {
        id: 'goal-travel',
        userId: user.id,
        name: '北歐獨旅基金',
        targetAmountMinor: 12000000,
        currentAmountMinor: 2400000,
        priority: 'medium',
        goalType: 'travel',
        monthlyContributionMinor: 0,
        status: 'active',
      },
      {
        id: 'goal-piano',
        userId: user.id,
        name: 'Roland FP-30X 基金',
        targetAmountMinor: 2500000,
        currentAmountMinor: 0,
        priority: 'medium',
        goalType: 'purchase',
        monthlyContributionMinor: 0,
        status: 'active',
      },
    ],
    recommendations: [],
    decisionHistory: [],
  }
}
